use_frameworks!

platform :ios, '8.0'

target 'BTVisualEffectView_Example' do
  pod 'BTVisualEffectView', :path => '../'

  target 'BTVisualEffectView_Tests' do
    inherit! :search_paths

    
  end
end
